### ISSUE TITLE
Error "Unable to find a checksum" occurs if install binary only

### ISSUE THREAD

**Issue by wellic** [githubixx/ansible-role-kubectl#34]
Issue occurs:
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to find a checksum for file 'kubectl' in 'https://cdn.dl.k8s.io/release/v1.28.1/bin/linux/amd64/kubectl.sha512'"}`
In the new release 23.0.0+1.28.1

In previous release [22.0.1+1.27.4](https://github.com/githubixx/ansible-role-kubectl/releases/tag/22.0.1%2B1.27.4) issue absent.
Also issue absent if  `kubectl_download_filetype: archive`

I've tested in Ubuntu and Debian.
Step To Reproduce:
- Run:
```bash 
ansible-galaxy role install githubixx.kubectl
```
- Create file `test.yaml`:
```yaml
- name: Install kubectl with githubixx.kubectl
  hosts: localhost
  connection: local
  tasks:
  - name: Install kubectl with githubixx.kubectl
    include_role:
      name: githubixx.kubectl
    vars:.
      kubectl_download_filetype: binary
```
- Run:
```bash 
ansible-playbook test.yaml
```
You will get 
```
ASK [githubixx.kubectl : Download kubectl binary] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to find a checksum for file 'kubectl' in 'https://cdn.dl.k8s.io/release/v1.28.1/bin/linux/amd64/kubectl.sha512'"}
```
